<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="Default.aspx.vb" Inherits="Salesforce4all._Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title>Salesforce4All</title>

     <!-- Global site tag (gtag.js) - Google Adesense -->
    <script data-ad-client="ca-pub-3393214826681796" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
     <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <link rel="icon" href="Images/index2.png">

     <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-109851018-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-109851018-1');
    </script>

   
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="css/modern-business.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="css/image-picker.css">

    <script src="scripts/jscolor.js"></script>

    <script src="scripts/jquery-1.7.1.min.js" type="text/javascript"></script>
    <script src="scripts/image-picker.min.js" type="text/javascript"></script>
    <script src="scripts/qrcode.min.js" type="text/javascript" ></script>
    <!--<script src="scripts/jquery.min.js" type="text/javascript"></script>-->



    <style>
        .thumbnail {
            margin-top: 10px;
            margin-left: 45px;
        }
        .card-header-salesforce {
          padding: 0.75rem 1.25rem;
          margin-bottom: 0;
          background-color: rgba(0, 136, 204, 0.7);
          border-bottom: 1px solid rgba(0, 0, 0, 0.125);
        }

        .spaced input[type="checkbox"] 
        {
           margin-right: 50px; /* Or any other value */
        }

        /* Generated by http://css.spritegen.com CSS Sprite Generator */
 

    </style>

   

</head>


<%--    https://startbootstrap.com/template-overviews/modern-business/--%>

<body onload="javascript:codeAddress();">

    <form id="form1" runat="server">

        <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
      
        <!-- Navigation -->
        <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
          <div class="container">
            <a class="navbar-brand" href="Default.aspx">Salesforce Awesome Certified</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="about.html">About</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>


        <!-- Page Content -->
        <div class="container">

           <%-- <h1 class="my-4">Welcome to the new way to generate your certificate logo</h1>--%>
            <h1 class="my-4">Generate your certificate logo for your LinkedIn profile or general purpose.</h1>

      
            <%--  <h2>Portfolio Heading</h2>--%>

            <div class="row">
                <div class="col-lg-4 col-sm-6 portfolio-item">
                    <div class="card h-100">
                        <a href="#">
                         <%--<img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>--%>
                         <img class="card-img-top" src="Images/header/oficial1.jpg" alt=""></a>
                        
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">Official Site</a>
                            </h4>
                            <!--<p class="card-text">To get salesforce certificate verification you can access throught official site on <a target="_blank" href="http://certification.salesforce.com/verification">Oficial Site</a></p>-->
                            <p class="card-text">To get salesforce certificate verification you can access throught official site on <a target="_blank" href="https://trailhead.salesforce.com/credentials/verification">Oficial Site</a></p>
                            
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 portfolio-item">
                    <div class="card h-100">
                        <a href="#">
                             <%--<img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>--%>
                         <img class="card-img-top" src="Images/header/old-model.jpg" alt=""></a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">Current Result</a>
                            </h4>
                            <p class="card-text">You get oficial result with your certificates.</p>
                        </div>
                    </div>
                </div>
                 <div class="col-lg-4 col-sm-6 portfolio-item">
                    <div class="card h-100">
                        <a href="#">
                            <%--<img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>--%>
                         <img class="card-img-top" src="Images/header/new-model.jpg" alt=""></a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">Awesome Result</a>
                            </h4>
                            <p class="card-text">Now you can get your image certificates in a nice way.</p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->

                      
            <div class="card my-4">
                        <h5 class="card-header-salesforce">How it works </h5>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-lg-12">
                                    <ul class="list-unstyled mb-0">
                                       <%-- <li>
                                                <asp:Label ID="lblMessage1" runat="server"></asp:Label>
                                        </li>--%>
                                        <li>
                                                  <b> Go ahead : </b>  This id is necesary to get the certificates . Follow this instructions:
                                            <br>
                                        </li>
                                        <br>
                                        <li>
                                                <p class="card-text"><b>1.</b> Go to official web salesforce credential <a target="_blank" href="https://trailhead.salesforce.com/credentials/verification">Verification Site</a></p>
                                        </li>
                                        <li>
                                                <p class="card-text"><b>2.</b> On <b>Verify a Salesforce Certified Professional</b> section. Then submit your <b>full name or email associated to webassesor</b> </p>
                                        </li>
                                        <li>
                                                <p class="card-text"><b>3.</b> Click on <b>Search button</b>.</p>
                                        </li>
                                        <li>
                                                <p class="card-text"><b>4.</b> Please complete the ReCaptcha. <b>I´m not a robot</b></p>
                                        </li>
                                          <li>
                                                <p class="card-text"><b>5.</b> Click on  <b>Show credentials</b></p>
                                        </li>
                                          <li>
                                                <p class="card-text"><b>6.</b> Click on  <b>Print Preview</b></p>
                                        </li>
                                          <li>
                                                <p class="card-text"><b>7.</b> It will open a new window with a url like this  <b><a target="_blank" href="https://trailhead.salesforce.com/credentials/certification-detail-print?searchString=oHaLnS4kEkdN+9z71CDD52gFYUAPU0cxLOFBekYnCYZh4ZroYmyH5VcweWknOsBC">Verification Site</a></b></p>
                                        </li>
                                         <li>
                                                <p class="card-text"><b>8.</b> Copy the searchString value at the end of url, it look like this:   <b>1RKVx8wH2FPaPqe6hKA6%2FL3UlBFlTXO6bNEIZLkpqvmycVnnROWZuzeOnIaTCl1M</b></p>
                                        </li>
                                         <li>
                                                <p class="card-text"><b>9. </b> Use this salesforce id  on step number #3 to get your beatiful image.</p>
                                        </li>
                                         <br>
                                        <li>
                                            <!--<iframe width="420" height="315" src="https://www.youtube.com/embed/hIC8P_KZ8Js" frameborder="0" gesture="media" allowfullscreen></iframe>-->
                                            <!--<iframe width="560" height="315" src="https://www.youtube.com/embed/iQV62TWIO9Y" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>-->
                                            <iframe width="560" height="315" src="https://www.youtube.com/embed/V2xcoVCfd0M" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                                            
                                        </li>
                                    </ul>
                                </div>
                              
                            </div>
                        </div>
                    </div>

             <div class="card my-4">
                        <h5 class="card-header-salesforce">Step 1 : Choose your favorite design !!! Pick on DropDown or Select an Image</h5>
             <hr />
                <!--<asp:Image ID="Image1" runat="server" Height = "100" Width = "100" />-->


                        <div class="card-body">
                            <div class="picker" id="drawZoneUploadFile" >
                                <select runat="server" title="Selecciona tu imagen preferida" class="image-picker show-labels show-html" id="imageSelected"  style="display: none">
                                    
                                    <option data-img-src='Images/12/header-bg-1.png' value='header-bg-1'>Cabin</option>
                                    <option data-img-src='Images/12/header-bg-2.png' value='header-bg-2'>Morning</option>
                                    <option data-img-src='Images/12/header-bg-3.png' value='header-bg-3'>Sun</option>
                                    <option data-img-src='Images/12/header-bg-4.png' value='header-bg-4'>Street</option>

                                    <option data-img-src='Images/12/header-bg-5.png' value='header-bg-5'>Lake</option>
                                    <option data-img-src='Images/12/header-bg-6.png' value='header-bg-6'>Universe</option>
                                    <option data-img-src='Images/12/header-bg-7.png' value='header-bg-7'>Autumn</option>
                                    <option data-img-src='Images/12/header-bg-8.png' value='header-bg-8'>Fjord</option>

                                    <option data-img-src='Images/12/header-bg-9.png' value='header-bg-9'>Hill</option>
                                    <option data-img-src='Images/12/header-bg-10.png' value='header-bg-10'>Immensity</option>
                                    <option data-img-src='Images/12/header-bg-11.png' value='header-bg-11'>Route</option>
                                    <option data-img-src='Images/12/header-bg-12.png' value='header-bg-12'>Calm</option>
        
                                    
                                    <option data-img-src='Images/12Trailhead/header-bg-1.png' value='header-bg-t1'>Forest</option>
                                    <option data-img-src='Images/12Trailhead/header-bg-2.png' value='header-bg-t2'>Sunrise</option>
                                    <option data-img-src='Images/12Trailhead/header-bg-3.png' value='header-bg-t3'>Morning</option>
                                    <option data-img-src='Images/12Trailhead/header-bg-4.png' value='header-bg-t4'>Night</option>
               
                                    <option data-img-src='Images/12/header-bg-13.png' value='header-bg-13'>Beach</option>
                                    <option data-img-src='Images/12/header-bg-14.png' value='header-bg-14'>Sun Flower</option>
                                    <option data-img-src='Images/12/header-bg-15.png' value='header-bg-15'>Red Carpet</option>
                                    <option data-img-src='Images/12/header-bg-16.png' value='header-bg-16'>Bridge</option>
               
                                    <option data-img-src='Images/12/Custom.png' value='ImgCustom' id="optionCustomImage" >Custom</option>
                                  
                            
                                   </select>
                            </div>

                                <h5 class="card-header-salesforce"> ... if you don't like any ... upload your own. If you choose a Custom design we recomend this size : 1500 x 320 pixeles with .png extension </h5>
                                <br />
                                <asp:FileUpload ID="FileUpload1" runat="server"  />
                                <asp:Button BackColor="Tomato" class="btn btn-primary" type="button" ID="btnUpload" runat="server" Text="Upload Image" OnClick="UploadFile" />
                              
                                <br />
                                <asp:Label ID="LabelUpload" runat="server" ForeColor ="Red" Font-Bold="true"  ></asp:Label>
                                <asp:Label ID="Label1" runat="server" ForeColor ="Black" Font-Bold="true"  > </asp:Label>
                         
                        </div>
                    </div>

             <div id="drawGenerateButtonSection"  class="card my-4">
                        <h5 class="card-header-salesforce">Step 2 : Select color title and Search your salesforce certificates by your ID associated to your salesforce account on webassesor</h5>
                        <div class="card-body">
                            <div class="row">
                                
                                <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <b>Email: </b> 
                                        </li>
                                        <li>
                                           <asp:TextBox runat="server" ID="email" class="form-control" placeholder="Example: Email@domain.com..."></asp:TextBox>
                                        </li>
                                    </ul>
                                </div>
                                 <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <b>Id Salesforce: Follow instructions in Step 1 to get this value</b> 
                                        </li>
                                        <li>
                                           <asp:TextBox runat="server" ID="idSalesforce" class="form-control" placeholder="Example: 1RKVx8wH2FPaPqe6hKA6%2FL3UlBFlTXO6bNEIZLkpqvmycVnnROWZuzeOnIaTCl1M"></asp:TextBox>

                                        </li>
                                    </ul>
                                </div>
                               
                            </div>
                             <br />

                            <div class="row">
                                <div class="col-lg-12">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <button class="form-control" style="border:2px solid gray"  data-jscolor="{valueElement:'chosen-value', onFineChange:'setTextColor(this)'}">
		                                        Pick title text color
	                                         </button>
                                        </li>
                                    </ul>
                                </div>
               
                            </div>
                             <br />
                            <div class="row">
                                <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <span class="input-group-btn">
                                                <asp:Button BackColor="Tomato" class="btn btn-primary" type="button" ID="Buscar" runat="server" Text="Generate your banner" OnClientClick="ga('send', 'event', 'PDF Downloads', 'Click', 'SEO For Beginners');" />
                                                <label for="male" id="busqueda" style="display:none ">Buscando ...</label>
                                             </span>
                                             <br />
                                             <asp:Label ID="LabelInputMessageValidation" runat="server" ForeColor ="Red" Font-Bold="true"  ></asp:Label>
                           
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>


                    <p></p>

             <!-- Content Row -->
              <div class="row" style="margin-top:50px">
                   <div class="col-lg-4 mb-4">
                    <h2>Share tool on different accounts</h2>
                    <p>More than 7000 people have used the tool. Share it so that the community can continue to grow</p>
                </div>

                <a href="https://twitter.com/intent/tweet?text=Generate your salesforce certificate banner at Salesforce4all. Site: http://salesforce4all.com/" data-size="small"  hashtags="Salesforce" >
                    <div class="col-lg-4 mb-4">
                      <div class="card h-50">
                        <h3 class="card-header" style="text-align:center">Twitter</h3>
                        <div class="card-body" style="width:150px;height:150px;text-align:center;margin-left:100px">
                           <img class="card-img-top" src="Images/Social/12/twitter.png" alt="" >
                        </div>
                        <ul class="list-group list-group-flush">
                          <li class="list-group-item"> 
                              <a href="https://twitter.com/intent/tweet?text=Generate your salesforce certificate banner at Salesforce4all. Site:" data-size="small"class="twitter-share-button" hashtags="Salesforce" >Tweet Salesforce4All</a>
                          </li>
                        </ul>
                      </div>
                    </div>
                </a>

                <div class="col-lg-4 mb-4">
                  <div class="card h-50">
                    <h3 class="card-header" style="text-align:center">LinkedIn</h3>
                    <div class="card-body" style="width:150px;height:150px;text-align:center;margin-left:100px">
                      <img class="card-img-top" src="Images/Social/12/linkedin.png" alt="">
                    </div>
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item">  
                         <script src="https://platform.linkedin.com/in.js" type="text/javascript">lang: en_US</script>
                         <script type="IN/Share" data-url="http://salesforce4all.com/"></script>
                      </li>
                    </ul>
                  </div>
                </div>
        </div>

             <div id="drawZoneNoResuts" style ="display:none" >

                    <div class="card my-4">
                        <h5 class="card-header-salesforce">Results</h5>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                                  <b> No search Results : </b>  No problem !! . Follow this instructions:
                                            <br>
                                        </li>
                                        <br>
                                        <li>
                                                <p class="card-text"><b>1.</b> Go to your webassessor account on  <a target="_blank" href="https://www.webassessor.com">WebAssesor</a></p>
                                        </li>
                                        <li>
                                                <p class="card-text"><b>2.</b> Set verification Opt-In value to <b>YES</b> </p>
                                        </li>
                                        <li>
                                                <p class="card-text"><b>3.</b> Copy <b>email address associated to your salesforce account</b>.</p>
                                        </li>
                                        <li>
                                                <p class="card-text"><b>4.</b> Paste email on search   <a target="_blank" href="http://certification.salesforce.com/verification">Salesforce Verification</a></p>
                                        </li>
                                          <li>
                                                <p class="card-text"><b>5.</b> Search again on this site and get your logo !!!</p>
                                        </li>
                                         <br>
                                        <li>
                                            <iframe width="420" height="315" src="https://www.youtube.com/embed/hIC8P_KZ8Js" frameborder="0" gesture="media" allowfullscreen></iframe>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <label>Your search for a certified professional has returned no results. Please confirm the full name or email address associated with this person's Salesforce.com Certification account and confirm they have selected to share their certification information.</label>
                                        </li>
                                        <li>
                                                <asp:Label ID="Label4" runat="server"></asp:Label>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                 </div>

            <div id="drawZone" style ="display:none" >

                  <div class="card my-4">
                        <h5 class="card-header-salesforce">Results</h5>
                        <div class="card-body">
                            <div class="row">
                                 <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <p>Congratulations! You have successfully completed the certification exams to become a Salesforce Certified.Welcome to the Salesforce worldwide community of Certified Professionals!   </p>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <b>Name: </b> 
                                                <asp:Label ID="lblName" runat="server"></asp:Label>
                                        </li>
                                        <li>
                                            <b>City: </b> 
                                                <asp:Label ID="lblCity" runat="server"></asp:Label>
                                        </li>
                                        <li>
                                            <b>Country: </b> 
                                                <asp:Label ID="lblCountry" runat="server"></asp:Label>
                                        </li>
                                        <li>
                                            <b>State: </b> 
                                                <asp:Label ID="lblState" runat="server"></asp:Label>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>

                

                    <div class="row">
                        <div id="container">
                            <canvas id="c" width="1200" height="320" style="border:2px solid gray"></canvas>
                        </div>
                    </div>

                 <!-- Call to Action Section -->
                    <div class="row mb-4" style="margin-top: 20px">
                          <div class="col-md-8">
                            <div class="row">
                            <div class="col-lg-2 col-sm-4 mb-4">
                              <img class="img-fluid" src="Images/browsers/logo-firefox.png" alt="">
                            </div>
                            <div class="col-lg-2 col-sm-4 mb-4">
                              <img class="img-fluid" src="Images/browsers/logo-opera.png" alt="">
                            </div>
                            <div class="col-lg-2 col-sm-4 mb-4">
                              <img class="img-fluid" src="Images/browsers/logo-safari.png" alt="">
                            </div>
                            <div class="col-lg-2 col-sm-4 mb-4">
                              <img class="img-fluid" src="Images/browsers/logo-chrome.png" alt="">
                            </div>
                          </div>
                          </div>
                        <div class="col-md-4">
                              <p>Feel Free to customize image, resize,reorient or move certificates. Choose Chrome,Firefox ,Opera or Safari Browser to save your logo  certificate.</p>
                            <a id="saveDownload" class="btn btn-primary" href="#" onclick="saveImg();" style="width:350px;background-color:tomato" >Save and Download your banner</a>
                        </div>
                    </div>



                      <div class="card my-4">
                        <h5 class="card-header-salesforce">Share the tool with others</h5>
                        <div class="card-body">
                            <div class="row">
                                 <div class="col-lg-12">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <b></b> 
                                        </li>
                                       
                                         <div class="card h-50">
                                                <!--<h3 class="card-header" style="text-align:center">LinkedIn</h3>
                                                <div class="card-body" style="width:150px;height:150px;text-align:center;margin-left:100px">
                                                  <img class="card-img-top" src="Images/Social/12/linkedin.png" alt="">
                                                </div>-->
                                                <ul class="list-group list-group-flush">
                                                  <li class="list-group-item">  
                                                     <script src="https://platform.linkedin.com/in.js" type="text/javascript">lang: en_US</script>
                                                     <script type="IN/Share" data-url="http://salesforce4all.com/"></script>
                                                  </li>
                                                </ul>
                                              </div>
                                    </ul>
                                </div>
                               
                            </div>
                                  
                        </div>
                    </div>




             
                 <div class="card my-4">
                        <h5 class="card-header-salesforce">You can download your QR code for your certificates</h5>
                        <div class="card-body">
                            <div class="row">
                                
                                <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <b>QR: </b> 
                                                  <asp:TextBox runat="server" id="textQr" class="form-control" placeholder=""></asp:TextBox>
                                                  <div id="qrcode" style="width:100px; height:100px; margin-top:15px;"></div>
                                        </li>
                                        <li>
                                        </li>
                                    </ul>
                                </div>
                                 <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <b>You can download a Qr code with link to Salesforce official site with your certificates. Make righ click over qr image and press Save image as option. Now you can share your QR code image at any location</b> 
                                        </li>
                                    </ul>
                                </div>
                               
                            </div>
                                  
                        </div>
                    </div>

                <div class="card my-4">
                        <h5 class="card-header-salesforce">Iframe</h5>
                        <div class="card-body">
                            <div class="row">
                                 <div class="col-lg-12">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <p>Now you can use an iframe on your website, now you can always keep up to date your cert logo!. Background parameter is a value from 0 to 14 </p>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-lg-12">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <p><b><asp:Literal ID="LiteralIframe" runat="server" ></asp:Literal></b></p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
          

           
            <!--   <div class="row" style="margin-top:50px;margin-bottom:50px" >
                <div class="col-lg-6">
                    <%--<img class="img-fluid rounded" src="http://placehold.it/700x450" alt="">--%>
                     <img class="img-fluid rounded" src="" alt="">
                    <a href="https://about.artisans.com.au/salesforce-certified-professional-artisan-hub-launch/#.WjvFxnmQzIU" target="_blank"> <img border="0" alt="Artisans" src="Images/Artisans.jpg" class="img-fluid rounded" > </a>
                </div>
                <div class="col-lg-6">
                    <h2>ARTISAN CONSULTING</h2>
                    <p>Welcome to the new way to generate your certificate logo In association with ARTISAN CONSULTING.</p>
                    <p>A certificate list and points score can also be accessed via Artisan Hub's Certified Professional Ranking and Regional Statistics Service.</p>
                    <p>Click   <a href="https://about.artisans.com.au/salesforce-certified-professional-artisan-hub-launch/#.WjvFxnmQzIU" target="_blank">here </a> for more information.</p>
                </div>
            </div>-->

      


            <!-- Features Section -->
            <div class="row" style="margin-top:50px;margin-bottom:50px" >
                <div class="col-lg-6">
                    <h2>Modern  Features</h2>
                    <p>The Modern  template is an image which could be use on:</p>
                    <ul>
                        <li>Footer template on your Email</li>
                        <li>Background image on your linkedIn profile </li>
                        <li>Header page on your personal professiona site</li>
                    </ul>
                    <p>Whatever your role, earning credentials from Salesforce shows that you have the ability to help transform companies by applying your knowledge to solve real-world challenges. The result? Salesforce-certified professionals aren't just in demand - they're increasingly indispensable.</p>
                </div>
                <div class="col-lg-6">
                    <%--<img class="img-fluid rounded" src="http://placehold.it/700x450" alt="">--%>
                     <img class="img-fluid rounded" src="Images/Email.jpg" alt="">
                </div>
            </div>
            <!-- /.row -->

              <h2>Many users have already used it in their Linked In background profile</h2>
                    <p></p>


              <div class="row"  style="margin-top:50px;margin-bottom:50px" >
                
                    <div class="col-md-3 col-sm-6 mb-4">
                      <a href="#">
                        <img class="img-fluid" src="/Images/LinkedIn/Linked4.png" alt="">
                      </a>
                    </div>

                    <div class="col-md-3 col-sm-6 mb-4">
                      <a href="#">
                        <img class="img-fluid" src="/Images/LinkedIn/Linked3.png" alt="">
                      </a>
                    </div>

                    <div class="col-md-3 col-sm-6 mb-4">
                      <a href="#">
                        <img class="img-fluid" src="/Images/LinkedIn/Linked2.png" alt="">
                      </a>
                    </div>

                    <div class="col-md-3 col-sm-6 mb-4">
                      <a href="#">
                        <img class="img-fluid" src="/Images/LinkedIn/Linked1.png" alt="">
                      </a>
                    </div>

                  </div>


              <h2>My Profile</h2>
                    <p></p>

             <!-- Content Row -->
              <div class="row" style="margin-top:50px">
                <div class="col-lg-4 mb-4">
                  <div class="card h-50">
                    <h3 class="card-header" style="text-align:center">Email</h3>
                    <div class="card-body" style="width:150px;height:150px;text-align:center;margin-left:100px">
                      <img class="card-img-top" src="Images/Social/12/gmail.png" alt="">
                    </div>
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item"> <a href="#">lordkortex@gmail.com</a></li>
                    </ul>
                  </div>
                </div>
                 <div class="col-lg-4 mb-4">
                  <div class="card h-50">
                    <h3 class="card-header" style="text-align:center">Skype</h3>
                    <div class="card-body" style="width:150px;height:150px;text-align:center;margin-left:100px">
                      <img class="card-img-top" src="Images/Social/12/skype.png" alt="">
                    </div>
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item"> <a href="#">Jhon Fredy Cortes Gaspar</a></li>
                    </ul>
                  </div>
                </div>
                 <div class="col-lg-4 mb-4">
                  <div class="card h-50">
                    <h3 class="card-header" style="text-align:center">LinkedIn</h3>
                    <div class="card-body" style="width:150px;height:150px;text-align:center;margin-left:100px">
                      <img class="card-img-top" src="Images/Social/12/linkedin.png" alt="">
                    </div>
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item">  <a target="_blank" href="https://www.linkedin.com/in/johncortes57">LinkedIn Profile</a></li>
                    </ul>
                  </div>
                </div>
              </div>

                <asp:TextBox runat="server" ID="TextBoxColor" Width="0"></asp:TextBox>
               <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" data-size="large" class="twitter-share-button" data-show-count="true">Tweet</a>

            <hr>
        </div>
        <!-- /.container -->

         <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Salesforce4All 2020</p>
      </div>
      <!-- /.container -->
    </footer>

        <img src="Images/12/Custom.png" id="ImgCustom" style="display: none;">
        <img src="Images/Original/header-bg-1.png" id="header-bg-1" style="display: none;">
        <img src="Images/Original/header-bg-2.png" id="header-bg-2" style="display: none;">
        <img src="Images/Original/header-bg-3.png" id="header-bg-3" style="display: none;">
        <img src="Images/Original/header-bg-4.png" id="header-bg-4" style="display: none;">

        <img src="Images/Original/header-bg-5.png" id="header-bg-5" style="display: none;">
        <img src="Images/Original/header-bg-6.png" id="header-bg-6" style="display: none;">
        <img src="Images/Original/header-bg-7.png" id="header-bg-7" style="display: none;">
        <img src="Images/Original/header-bg-8.png" id="header-bg-8" style="display: none;">

        <img src="Images/Original/header-bg-9.png" id="header-bg-9" style="display: none;">
        <img src="Images/Original/header-bg-10.png" id="header-bg-10" style="display: none;">
        <img src="Images/Original/header-bg-11.png" id="header-bg-11" style="display: none;">
        <img src="Images/Original/header-bg-12.png" id="header-bg-12" style="display: none;">

        <img src="Images/Original/header-bg-13.png" id="header-bg-13" style="display: none;">
        <img src="Images/Original/header-bg-14.png" id="header-bg-14" style="display: none;">
        <img src="Images/Original/header-bg-15.png" id="header-bg-15" style="display: none;">
        <img src="Images/Original/header-bg-16.png" id="header-bg-16" style="display: none;">

        <img src="Images/OriginalTrailhead/header-bg-1.png" id="header-bg-t1" style="display: none;">
        <img src="Images/OriginalTrailhead/header-bg-2.png" id="header-bg-t2" style="display: none;">
        <img src="Images/OriginalTrailhead/header-bg-3.png" id="header-bg-t3" style="display: none;">
        <img src="Images/OriginalTrailhead/header-bg-4.png" id="header-bg-t4" style="display: none;">


         <img src="Images/Certificates/.cert-badge.Certified.Administrator-min.jpg" id="Salesforce Certified Administrator" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Advanced.Administrator-min.jpg" id="Salesforce Certified Advanced Administrator" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Sales.Consultant-min.jpg" id="Salesforce Certified Sales Cloud Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Service.Consultant-min.jpg" id="Salesforce Certified Service Cloud Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Technical.Architect-min.jpg" id="Salesforce Certified Technical Architect" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.System.Architect-min.jpg" id="Salesforce Certified System Architect" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Application.Architect-min.jpg" id="Salesforce Certified Application Architect" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Pardot.Consultant-min.jpg" id="Salesforce Certified Pardot Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Pardot.User-min.jpg" id="Salesforce Certified Pardot Specialist" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.App.Builder-min.jpg" id="Salesforce Certified Platform App Builder" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Marketing.Cloud.Email.Specialist-min.jpg" id="Salesforce Certified Marketing Cloud Email Specialist" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Marketing.Cloud.Social.Specialist-min.jpg" id="Certified Marketing Cloud Social Specialist" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Programmer.I-min.jpg" id="Salesforce Certified Platform Developer I" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Programmer.II-min.jpg" id="Salesforce Certified Platform Developer II" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Data.Architecture.and.Management.Specialist-min.jpg" id="Salesforce Certified Data Architecture & Management Designer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Data.Architecture.and.Management.Specialist-min.jpg" id="Salesforce Certified Data Architecture and Management Designer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Development.Lifecycle.and.Deployment.Specialist-min.jpg" id="Salesforce Certified Development Lifecycle and Deployment Designer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Integration.Architecture.Specialist-min.jpg" id="Salesforce Certified Integration Architecture Designer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Marketing.Cloud.Consultant-min.jpg" id="Salesforce Certified Marketing Cloud Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Marketing.Cloud.Developer-min.jpg" id="Salesforce Certified Marketing Cloud Developer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Sharing.and.Visibility.Designer-min.jpg" id="Salesforce Certified Sharing and Visibility Designer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Identity.and.Access.Management.Designer-min.jpg" id="Salesforce Certified Identity and Access Management Designer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Mobile.Solutions.Architecture.Designer-min.jpg" id="Salesforce Certified Mobile Solutions Architecture Designer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Community.Cloud.Consultant-min.jpg" id="Salesforce Certified Community Cloud Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.CPQ.Specialist-min.jpg" id="Salesforce Certified CPQ Specialist" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Accredited.Sales.Professional-min.jpg" id="Accredited Sales Professional" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Accredited.Presales.Professional-min.jpg" id="Accredited Presales Professional" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Nonprofit.Cloud.Consultant-min.jpg" id="Salesforce Certified Nonprofit Cloud Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Field.Service.Lightning.Consultant-min.jpg" id="Salesforce Certified Field Service Lightning" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Field.Service.Lightning.Consultant-min.jpg" id="Salesforce Certified Field Service Lightning Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Einstein.Analytics.Discovery.Consultant-min.png" id="Salesforce Certified Einstein Analytics and Discovery Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Education.Cloud.Consultant-min.jpg " id="Salesforce Certified Education Cloud Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Heroku.Architecture.Designer-min.png" id="Salesforce Certified Heroku Architecture Designer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Salesforce.Certified.Marketing.Cloud.Administrator-min.jpg" id="Salesforce Certified Marketing Cloud Administrator" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.B2C.Commerce.Developer-min.jpg" id="Salesforce Certified B2C Commerce Developer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.B2C.Commerce.Technical.Solution.Designer-min.jpg" id="Salesforce Certified B2C Technical Solution Designer" style="display: none;">
        <img src="Images/Certificates/Salesforce Accredited B2B Commerce Developer-min.png" id="Salesforce Accredited B2B Commerce Developer" style="display: none;">
        <img src="Images/Certificates/Salesforce Accredited B2B Commerce Administrator-min.png" id="Salesforce Accredited B2B Commerce Administrator" style="display: none;">
        <img src="Images/Certificates/Salesforce Certified B2C Commerce Architect-min.png" id="Salesforce Certified B2C Commerce Architect" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Salesforce.Certified.Marketing.Cloud.Administrator-min.jpg" id="Img2" style="display: none;">
        

        <script src="Scripts/fabric.min.js" type="text/javascript"></script>

        <script type="text/javascript">

            function redirect() {
                window.open("http://www.salesforce4all.com/Default.aspx#drawZone?email=" + document.getElementById("email").value + "&indexBackground=" + document.getElementById("imageSelected").selectedIndex, '_blank');
            }

            jQuery("select.image-picker").imagepicker({
                hide_select: false,
            });

            jQuery("select.image-picker.show-labels").imagepicker({
                hide_select: false,
                show_label: true,
            });

            jQuery("select.image-picker.limit_callback").imagepicker({
                limit_reached: function () { alert('We are full!') },
                hide_select: false
            });

            var container = jQuery("select.image-picker.masonry").next("ul.thumbnails");
            container.imagesLoaded(function () {
                container.masonry({
                    itemSelector: "li",
                });
            });

        </script>
    </form>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


   <script type="text/javascript">
       var qrcode = new QRCode(document.getElementById("qrcode"), {
           width: 100,
           height: 100
       });

       function makeCode() {
           var elText = document.getElementById("textQr");
           qrcode.makeCode(elText.value);
       }

       makeCode();
    </script>

    <script type="text/javascript">
    	    function setTextColor(picker) {
    	        document.getElementById("TextBoxColor").value = '#' + picker.toString();
    	        
    	    }
	</script>

    <script type="text/javascript" async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

</body>
</html>
