<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="Default.aspx.vb" Inherits="Salesforce4all._Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title>Salesforce4All</title>

    <link rel="icon" href="Images/index2.png">

     <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-109851018-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-109851018-1');
    </script>


    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="css/modern-business.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="css/image-picker.css">

    <script src="scripts/jquery-1.7.1.min.js" type="text/javascript"></script>
    <script src="scripts/image-picker.min.js" type="text/javascript"></script>
    <script src="scripts/qrcode.min.js" type="text/javascript" ></script>
    <!--<script src="scripts/jquery.min.js" type="text/javascript"></script>-->

    <style>
        .thumbnail {
            margin-top: 10px;
            margin-left: 45px;
        }
        .card-header-salesforce {
          padding: 0.75rem 1.25rem;
          margin-bottom: 0;
          background-color: rgba(0, 136, 204, 0.7);
          border-bottom: 1px solid rgba(0, 0, 0, 0.125);
        }

        .spaced input[type="checkbox"] 
        {
           margin-right: 50px; /* Or any other value */
        }

        /* Generated by http://css.spritegen.com CSS Sprite Generator */
 
/*.cert-badge-certified-commerce-cloud-digital-developer, .cert-badge-certified-administrator, .cert-badge-certified-advanced-administrator, .cert-badge-certified-app-builder, .cert-badge-certified-cpq-specialist, 
.cert-badge-certified-development-lifecycle-and-deployment-specialist, .cert-badge-certified-field-service-lightning-consultant, .cert-badge-certified-integration-architecture-specialist, .cert-badge-certified-marketing-cloud-email-specialist, .cert-badge-certified-pardot-consultant, 
.cert-badge-certified-pardot-user, .cert-badge-certified-sales-consultant, .cert-badge-certified-service-consultant, .cert-badge-accredited-presales-professional, .cert-badge-accredited-sales-professional, 
.cert-badge-certified-advanced-developer, .cert-badge-certified-application-architect, .cert-badge-certified-community-cloud-consultant, .cert-badge-certified-data-architecture-and-management-specialist, .cert-badge-certified-developer, 
.cert-badge-certified-identity-and-access-management-designer, .cert-badge-certified-marketing-cloud-consultant, .cert-badge-certified-marketing-cloud-social-specialist, .cert-badge-certified-mobile-solutions-architecture-designer, .cert-badge-certified-programmer-i, 
.cert-badge-certified-programmer-ii, .cert-badge-certified-sharing-and-visibility-designer, .cert-badge-certified-system-architect, .cert-badge-certified-technical-architect
{ display: inline-block; background: url('png.png') no-repeat; overflow: hidden; text-indent: -9999px; text-align: left; }
 
.cert-badge-certified-commerce-cloud-digital-developer { background-position: -0px -0px; width: 364px; height: 203px; }
.cert-badge-certified-administrator { background-position: -0px -203px; width: 355px; height: 203px; }
.cert-badge-certified-advanced-administrator { background-position: -0px -406px; width: 355px; height: 203px; }
.cert-badge-certified-app-builder { background-position: -0px -609px; width: 355px; height: 203px; }
.cert-badge-certified-cpq-specialist { background-position: -0px -812px; width: 355px; height: 203px; }
.cert-badge-certified-development-lifecycle-and-deployment-specialist { background-position: -0px -1015px; width: 355px; height: 203px; }
.cert-badge-certified-field-service-lightning-consultant { background-position: -0px -1218px; width: 355px; height: 203px; }
.cert-badge-certified-integration-architecture-specialist { background-position: -0px -1421px; width: 355px; height: 203px; }
.cert-badge-certified-marketing-cloud-email-specialist { background-position: -0px -1624px; width: 355px; height: 203px; }
.cert-badge-certified-pardot-consultant { background-position: -0px -1827px; width: 355px; height: 203px; }
.cert-badge-certified-pardot-user { background-position: -0px -2030px; width: 355px; height: 203px; }
.cert-badge-certified-sales-consultant { background-position: -0px -2233px; width: 355px; height: 203px; }
.cert-badge-certified-service-consultant { background-position: -0px -2436px; width: 355px; height: 203px; }
.cert-badge-accredited-presales-professional { background-position: -0px -2639px; width: 354px; height: 202px; }
.cert-badge-accredited-sales-professional { background-position: -0px -2841px; width: 354px; height: 202px; }
.cert-badge-certified-advanced-developer { background-position: -0px -3043px; width: 354px; height: 203px; }
.cert-badge-certified-application-architect { background-position: -0px -3246px; width: 354px; height: 203px; }
.cert-badge-certified-community-cloud-consultant { background-position: -0px -3449px; width: 354px; height: 203px; }
.cert-badge-certified-data-architecture-and-management-specialist { background-position: -0px -3652px; width: 354px; height: 203px; }
.cert-badge-certified-developer { background-position: -0px -3855px; width: 354px; height: 203px; }
.cert-badge-certified-identity-and-access-management-designer { background-position: -0px -4058px; width: 354px; height: 203px; }
.cert-badge-certified-marketing-cloud-consultant { background-position: -0px -4261px; width: 354px; height: 203px; }
.cert-badge-certified-marketing-cloud-social-specialist { background-position: -0px -4464px; width: 354px; height: 203px; }
.cert-badge-certified-mobile-solutions-architecture-designer { background-position: -0px -4667px; width: 354px; height: 203px; }
.cert-badge-certified-programmer-i { background-position: -0px -4870px; width: 354px; height: 203px; }
.cert-badge-certified-programmer-ii { background-position: -0px -5073px; width: 354px; height: 203px; }
.cert-badge-certified-sharing-and-visibility-designer { background-position: -0px -5276px; width: 354px; height: 203px; }
.cert-badge-certified-system-architect { background-position: -0px -5479px; width: 354px; height: 203px; }
.cert-badge-certified-technical-architect { background-position: -0px -5682px; width: 354px; height: 203px; }*/
    </style>

   

</head>


<%--    https://startbootstrap.com/template-overviews/modern-business/--%>

<body onload="javascript:codeAddress();">
    <form id="form1" runat="server">


        <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>


      
        <!-- Navigation -->
        <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
          <div class="container">
            <a class="navbar-brand" href="Default.aspx">Salesforce Awesome Certified</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="about.html">About</a>
                </li>
<%--                <li class="nav-item">
                  <a class="nav-link" href="services.html">Services</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="contact.html">Contact</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Portfolio
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                    <a class="dropdown-item" href="portfolio-1-col.html">1 Column Portfolio</a>
                    <a class="dropdown-item" href="portfolio-2-col.html">2 Column Portfolio</a>
                    <a class="dropdown-item" href="portfolio-3-col.html">3 Column Portfolio</a>
                    <a class="dropdown-item" href="portfolio-4-col.html">4 Column Portfolio</a>
                    <a class="dropdown-item" href="portfolio-item.html">Single Portfolio Item</a>
                  </div>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Blog
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
                    <a class="dropdown-item" href="blog-home-1.html">Blog Home 1</a>
                    <a class="dropdown-item" href="blog-home-2.html">Blog Home 2</a>
                    <a class="dropdown-item" href="blog-post.html">Blog Post</a>
                  </div>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="A1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Other Pages
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
                    <a class="dropdown-item" href="full-width.html">Full Width Page</a>
                    <a class="dropdown-item" href="sidebar.html">Sidebar Page</a>
                    <a class="dropdown-item" href="faq.html">FAQ</a>
                    <a class="dropdown-item" href="404.html">404</a>
                    <a class="dropdown-item" href="pricing.html">Pricing Table</a>
                  </div>
                </li>--%>
              </ul>
            </div>
          </div>
        </nav>



        <header>
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <!-- Slide One - Set the background image for this slide in the line below -->
          <div class="carousel-item active" style="background-image: url('Images/Index2.jpg')">
            <div class="carousel-caption d-none d-md-block">
              <h3></h3>
              <p></p>
            </div>
          </div>
          <!-- Slide Two - Set the background image for this slide in the line below -->
          <div class="carousel-item" style="background-image: url('Images/Index1.jpg')">
            <div class="carousel-caption d-none d-md-block">
              <h3></h3>
              <p>T</p>
            </div>
          </div>
          <!-- Slide Three - Set the background image for this slide in the line below -->
          <div class="carousel-item" style="background-image: url('Images/Index3.jpg')">
            <div class="carousel-caption d-none d-md-block">
              <h3></h3>
              <p></p>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </header>




        <!-- Page Content -->
        <div class="container">

           <%-- <h1 class="my-4">Welcome to the new way to generate your certificate logo</h1>--%>
            <h1 class="my-4">Generate your certificate logo for your LinkedIn profile or general purpose.</h1>

            


            <%--  <h2>Portfolio Heading</h2>--%>

            <div class="row">
                <div class="col-lg-4 col-sm-6 portfolio-item">
                    <div class="card h-100">
                        <a href="#">
                         <%--<img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>--%>
                         <img class="card-img-top" src="Images/oficial1.jpg" alt=""></a>
                        
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">Official Site</a>
                            </h4>
                            <!--<p class="card-text">To get salesforce certificate verification you can access throught official site on <a target="_blank" href="http://certification.salesforce.com/verification">Oficial Site</a></p>-->
                            <p class="card-text">To get salesforce certificate verification you can access throught official site on <a target="_blank" href="https://trailhead.salesforce.com/credentials/verification">Oficial Site</a></p>
                            
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 portfolio-item">
                    <div class="card h-100">
                        <a href="#">
                             <%--<img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>--%>
                         <img class="card-img-top" src="Images/old-model.jpg" alt=""></a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">Current Result</a>
                            </h4>
                            <p class="card-text">You get oficial result with your certificates.</p>
                        </div>
                    </div>
                </div>
                 <div class="col-lg-4 col-sm-6 portfolio-item">
                    <div class="card h-100">
                        <a href="#">
                            <%--<img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>--%>
                         <img class="card-img-top" src="Images/new-model.jpg" alt=""></a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">Awesome Result</a>
                            </h4>
                            <p class="card-text">Now you can get your image certificates in a nice way.</p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->


             <div class="card my-4">
                        <h5 class="card-header-salesforce">Step 1 : Choose your favorite design !!!</h5>
                        <div class="card-body">
                            <div class="picker">
                                <select runat="server" title="Selecciona tu imagen preferida" class="image-picker show-labels show-html" id="imageSelected"  style="display: none">
                                    <option data-img-src='Images/12/header-bg-1.png' value='header-bg-1'>Cabin</option>
                                    <option data-img-src='Images/12/header-bg-2.png' value='header-bg-2'>Morning</option>
                                    <option data-img-src='Images/12/header-bg-3.png' value='header-bg-3'>Sun</option>
                                    <option data-img-src='Images/12/header-bg-4.png' value='header-bg-4'>Street</option>

                                    <option data-img-src='Images/12/header-bg-5.png' value='header-bg-5'>Lake</option>
                                    <option data-img-src='Images/12/header-bg-6.png' value='header-bg-6'>Universe</option>
                                    <option data-img-src='Images/12/header-bg-7.png' value='header-bg-7'>Autumn</option>
                                    <option data-img-src='Images/12/header-bg-8.png' value='header-bg-8'>Fjord</option>

                                    <option data-img-src='Images/12/header-bg-9.png' value='header-bg-9'>Hill</option>
                                    <option data-img-src='Images/12/header-bg-10.png' value='header-bg-10'>Immensity</option>
                                    <option data-img-src='Images/12/header-bg-11.png' value='header-bg-11'>Route</option>
                                    <option data-img-src='Images/12/header-bg-12.png' value='header-bg-12'>Calm</option>
        
                                    
                                    <option data-img-src='Images/12Trailhead/header-bg-1.png' value='header-bg-t1'>Forest</option>
                                    <option data-img-src='Images/12Trailhead/header-bg-2.png' value='header-bg-t2'>Sunrise</option>
                                    <option data-img-src='Images/12Trailhead/header-bg-3.png' value='header-bg-t3'>Morning</option>
                                    <option data-img-src='Images/12Trailhead/header-bg-4.png' value='header-bg-t4'>Night</option>
               
                                    <option data-img-src='Images/12/header-bg-13.png' value='header-bg-13'>Beach</option>
                                    <option data-img-src='Images/12/header-bg-14.png' value='header-bg-14'>Sun Flower</option>
                                    <option data-img-src='Images/12/header-bg-15.png' value='header-bg-15'>Red Carpet</option>
                                    <option data-img-src='Images/12/header-bg-16.png' value='header-bg-16'>Bridge</option>
               
                            
                                   </select>
                            </div>
                        </div>
                    </div>
            <%--
                    <div class="card my-4">
                        <h5 class="card-header-salesforce">Step 2 : Choose your certificates !!!</h5>
                        <div class="card-body">
                            <div class="picker">
                               <asp:CheckBoxList ID="CheckBoxList1" runat="server"
                                       CellPadding="1500"
                                       CellSpacing="1500"
                                       RepeatColumns="5"
                                       RepeatDirection="Vertical"
                                       RepeatLayout="Flow"
                                       TextAlign="Right"
                                       CssClass="spaced"
                                       DataTextField ="language" DataValueField="language" 
                                       AutoPostBack  ="False">  
                                  
                                    <asp:ListItem Value="Text1" Text="Text2" >COBOL</asp:ListItem> 
                                 
                                        <img src="Images/Certificates/.cert-badge.Certified.Administrator.jpg" id="Img1" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Advanced.Administrator.jpg" id="Img2" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Advanced.Developer.jpg" id="Img3" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Developer.jpg" id="Img4" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Sales.Consultant.jpg" id="Img5" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Service.Consultant.jpg" id="Img6" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Technical.Architect.jpg" id="Img7" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.System.Architect.jpg" id="Img8" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Application.Architect.jpg" id="Img9" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Pardot.Consultant.jpg" id="Img10" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Pardot.User.jpg" id="Img11" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.App.Builder.jpg" id="Img12" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Marketing.Cloud.Email.Specialist.jpg" id="Img13" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Marketing.Cloud.Social.Specialist.jpg" id="Img14" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Programmer.I.jpg" id="Img15" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Programmer.II.jpg" id="Img16" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Data.Architecture.and.Management.Specialist.jpg" id="Img17" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Development.Lifecycle.and.Deployment.Specialist.jpg" id="Img18" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Integration.Architecture.Specialist.jpg" id="Img19" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Marketing.Cloud.Consultant.jpg" id="Img20" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Sharing.and.Visibility.Designer.jpg" id="Img21" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Identity.and.Access.Management.Designer.jpg" id="Img22" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Mobile.Solutions.Architecture.Designer.jpg" id="Img23" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Community.Cloud.Consultant.jpg" id="Img24" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.CPQ.Specialist.jpg" id="Img25" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Field.Service.Lightning.Consultant.jpg" id="Img26" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Certified.Commerce.Cloud.Digital.Developer.jpg" id="Img27" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Accredited.Sales.Professional.jpg" id="Img28" style="display: none;">
                                        <img src="Images/Certificates/.cert-badge.Accredited.Presales.Professional.jpg" id="Img29" style="display: none;">

                                </asp:CheckBoxList> 
                            </div>
                        </div>
                    </div>
               --%>
             
          
                     <div class="card my-4">
                        <h5 class="card-header-salesforce">Step 2: Search your salesforce account id</h5>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-lg-12">
                                    <ul class="list-unstyled mb-0">
                                       <%-- <li>
                                                <asp:Label ID="lblMessage1" runat="server"></asp:Label>
                                        </li>--%>
                                        <li>
                                                  <b> Go ahead : </b>  This id is necesary to get the certificates . Follow this instructions:
                                            <br>
                                        </li>
                                        <br>
                                        <li>
                                                <p class="card-text"><b>1.</b> Go to official web salesforce credential <a target="_blank" href="https://trailhead.salesforce.com/credentials/verification">Verification Site</a></p>
                                        </li>
                                        <li>
                                                <p class="card-text"><b>2.</b> On <b>Verify a Salesforce Certified Professional</b> section. Then submit your <b>full name or email associated to webassesor</b> </p>
                                        </li>
                                        <li>
                                                <p class="card-text"><b>3.</b> Click on <b>Search button</b>.</p>
                                        </li>
                                        <li>
                                                <p class="card-text"><b>4.</b> Please complete the ReCaptcha. <b>I´m not a robot</b></p>
                                        </li>
                                          <li>
                                                <p class="card-text"><b>5.</b> Click on  <b>Show credentials</b></p>
                                        </li>
                                          <li>
                                                <p class="card-text"><b>6.</b> Click on  <b>Print Preview</b></p>
                                        </li>
                                          <li>
                                                <p class="card-text"><b>7.</b> It will open a new window with a url like this  <b><a target="_blank" href="https://trailhead.salesforce.com/credentials/certification-detail-print?searchString=1RKVx8wH2FPaPqe6hKA6%2FL3UlBFlTXO6bNEIZLkpqvmycVnnROWZuzeOnIaTCl1M">Verification Site</a></b></p>
                                        </li>
                                         <li>
                                                <p class="card-text"><b>8.</b> Copy the searchString value at the end of url, it look like this:   <b>1RKVx8wH2FPaPqe6hKA6%2FL3UlBFlTXO6bNEIZLkpqvmycVnnROWZuzeOnIaTCl1M</b></p>
                                        </li>
                                         <li>
                                                <p class="card-text"><b>9. </b> Use this salesforce id  in next step to get your beatiful image.</p>
                                        </li>
                                         <br>
                                        <li>
                                            <!--<iframe width="420" height="315" src="https://www.youtube.com/embed/hIC8P_KZ8Js" frameborder="0" gesture="media" allowfullscreen></iframe>-->
                                            <iframe width="560" height="315" src="https://www.youtube.com/embed/iQV62TWIO9Y" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                                        </li>
                                    </ul>
                                </div>
                              
                            </div>
                        </div>
                    </div>

             <div class="card my-4">
                        <h5 class="card-header-salesforce">Step 3 : Search your salesforce certificates by your ID associated to your salesforce account on webassesor</h5>
                        <div class="card-body">
                            <div class="row">
                                
                                <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <b>Email: </b> 
                                        </li>
                                        <li>
                                           <asp:TextBox runat="server" ID="email" class="form-control" placeholder="Example: Email@domain.com..."></asp:TextBox>
                                        </li>
                                    </ul>
                                </div>
                                 <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <b>Id Salesforce: Follow instructions in Step 2 to get this value</b> 
                                        </li>
                                        <li>
                                           <asp:TextBox runat="server" ID="idSalesforce" class="form-control" placeholder="Example: 1RKVx8wH2FPaPqe6hKA6%2FL3UlBFlTXO6bNEIZLkpqvmycVnnROWZuzeOnIaTCl1M"></asp:TextBox>

                                        </li>
                                    </ul>
                                </div>
                               
                            </div>
                            <br />
                             <span class="input-group-btn">
                                <asp:Button BackColor="Tomato" class="btn btn-primary" type="button" ID="Buscar" runat="server" Text="Generate Image" OnClientClick="ga('send', 'event', 'PDF Downloads', 'Click', 'SEO For Beginners');" />
                                <label for="male" id="busqueda" style="display:none ">Buscando ...</label>
                             </span>
                             <br />
                             <asp:Label ID="LabelInputMessageValidation" runat="server" ForeColor ="Red" Font-Bold="true"  ></asp:Label>
                            
                        </div>
                    </div>



             <div id="drawZoneNoResuts" style ="display:none" >

                    <div class="card my-4">
                        <h5 class="card-header-salesforce">Step 3: Results</h5>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                       <%-- <li>
                                                <asp:Label ID="lblMessage1" runat="server"></asp:Label>
                                        </li>--%>
                                        <li>
                                                  <b> No search Results : </b>  No problem !! . Follow this instructions:
                                            <br>
                                        </li>
                                        <br>
                                        <li>
                                                <p class="card-text"><b>1.</b> Go to your webassessor account on  <a target="_blank" href="https://www.webassessor.com">WebAssesor</a></p>
                                        </li>
                                        <li>
                                                <p class="card-text"><b>2.</b> Set verification Opt-In value to <b>YES</b> </p>
                                        </li>
                                        <li>
                                                <p class="card-text"><b>3.</b> Copy <b>email address associated to your salesforce account</b>.</p>
                                        </li>
                                        <li>
                                                <p class="card-text"><b>4.</b> Paste email on search   <a target="_blank" href="http://certification.salesforce.com/verification">Salesforce Verification</a></p>
                                        </li>
                                          <li>
                                                <p class="card-text"><b>5.</b> Search again on this site and get your logo !!!</p>
                                        </li>
                                         <br>
                                        <li>
                                            <iframe width="420" height="315" src="https://www.youtube.com/embed/hIC8P_KZ8Js" frameborder="0" gesture="media" allowfullscreen></iframe>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <%--<asp:Label ID="lblMessage3" runat="server"></asp:Label>--%>
                                            <label>Your search for a certified professional has returned no results. Please confirm the full name or email address associated with this person's Salesforce.com Certification account and confirm they have selected to share their certification information.</label>
                                        </li>
                                        <li>
                                                <asp:Label ID="Label4" runat="server"></asp:Label>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                 </div>

            <div id="drawZone" style ="display:none" >

                  <div class="card my-4">
                        <h5 class="card-header-salesforce">Step 4: Results</h5>
                        <div class="card-body">
                            <div class="row">
                                 <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <p>Congratulations! You have successfully completed the certification exams to become a Salesforce Certified.Welcome to the Salesforce worldwide community of Certified Professionals!   </p>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <b>Name: </b> 
                                                <asp:Label ID="lblName" runat="server"></asp:Label>
                                        </li>
                                        <li>
                                            <b>City: </b> 
                                                <asp:Label ID="lblCity" runat="server"></asp:Label>
                                        </li>
                                        <li>
                                            <b>Country: </b> 
                                                <asp:Label ID="lblCountry" runat="server"></asp:Label>
                                        </li>
                                        <li>
                                            <b>State: </b> 
                                                <asp:Label ID="lblState" runat="server"></asp:Label>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>


                   <div class="card my-4">
                        <h5 class="card-header-salesforce">Step 5: Iframe</h5>
                        <div class="card-body">
                            <div class="row">
                                 <div class="col-lg-12">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <p>Now you can use an iframe on your website, now you can always keep up to date your cert logo!. Background parameter is a value from 0 to 14 </p>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-lg-12">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <p><b><asp:Literal ID="LiteralIframe" runat="server" ></asp:Literal></b></p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>


                 <div class="card my-4">
                        <h5 class="card-header-salesforce">Step 6 : You can download your QR code for your certificates</h5>
                        <div class="card-body">
                            <div class="row">
                                
                                <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <b>QR: </b> 
                                                  <asp:TextBox runat="server" id="textQr" class="form-control" placeholder=""></asp:TextBox>
                                                  <div id="qrcode" style="width:100px; height:100px; margin-top:15px;"></div>
                                        </li>
                                        <li>
                                        </li>
                                    </ul>
                                </div>
                                 <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <b>You can download a Qr code with link to Salesforce official site with your certificates. Make righ click over qr image and press Save image as option. Now you can share your QR code image at any location</b> 
                                        </li>
                                       
                                    </ul>
                                </div>
                               
                            </div>
                                  
                        </div>
                    </div>



                    <div class="row">
                        <div id="container">
                            <canvas id="c" width="1200" height="320"></canvas>
                        </div>
                    </div>



                    <!-- Call to Action Section -->
                    <div class="row mb-4" style="margin-top: 20px">
                          <div class="col-md-8">
                            <div class="row">
                            <div class="col-lg-2 col-sm-4 mb-4">
                              <img class="img-fluid" src="Images/browsers/logo-firefox.png" alt="">
                            </div>
                            <div class="col-lg-2 col-sm-4 mb-4">
                              <img class="img-fluid" src="Images/browsers/logo-opera.png" alt="">
                            </div>
                            <div class="col-lg-2 col-sm-4 mb-4">
                              <img class="img-fluid" src="Images/browsers/logo-safari.png" alt="">
                            </div>
                            <div class="col-lg-2 col-sm-4 mb-4">
                              <img class="img-fluid" src="Images/browsers/logo-chrome.png" alt="">
                            </div>
                          </div>
                          </div>
                        <div class="col-md-4">
                              <p>Feel Free to customize image, resize,reorient or move certificates. Choose Chrome,Firefox ,Opera or Safari Browser to save your logo  certificate.</p>
                            <a class="btn btn-primary" href="#" onclick="saveImg();" style="width:350px " >Save Image</a>
                        </div>
                    </div>

            </div>
          

           
               <div class="row" style="margin-top:50px;margin-bottom:50px" >
                <div class="col-lg-6">
                    <%--<img class="img-fluid rounded" src="http://placehold.it/700x450" alt="">--%>
                     <img class="img-fluid rounded" src="" alt="">
                    <a href="https://about.artisans.com.au/salesforce-certified-professional-artisan-hub-launch/#.WjvFxnmQzIU" target="_blank"> <img border="0" alt="Artisans" src="Images/Artisans.jpg" class="img-fluid rounded" > </a>
                </div>
                <div class="col-lg-6">
                    <h2>ARTISAN CONSULTING</h2>
                    <p>Welcome to the new way to generate your certificate logo In association with ARTISAN CONSULTING.</p>
                    <p>A certificate list and points score can also be accessed via Artisan Hub's Certified Professional Ranking and Regional Statistics Service.</p>
                    <p>Click   <a href="https://about.artisans.com.au/salesforce-certified-professional-artisan-hub-launch/#.WjvFxnmQzIU" target="_blank">here </a> for more information.</p>
                </div>
            </div>

      


            <!-- Features Section -->
            <div class="row" style="margin-top:50px;margin-bottom:50px" >
                <div class="col-lg-6">
                    <h2>Modern  Features</h2>
                    <p>The Modern  template is an image which could be use on:</p>
                    <ul>
                        <li>Footer template on your Email</li>
                        <li>Background image on your linkedIn profile </li>
                        <li>Header page on your personal professiona site</li>
                    </ul>
                    <p>Whatever your role, earning credentials from Salesforce shows that you have the ability to help transform companies by applying your knowledge to solve real-world challenges. The result? Salesforce-certified professionals aren't just in demand - they're increasingly indispensable.</p>
                </div>
                <div class="col-lg-6">
                    <%--<img class="img-fluid rounded" src="http://placehold.it/700x450" alt="">--%>
                     <img class="img-fluid rounded" src="Images/Email.jpg" alt="">
                </div>
            </div>
            <!-- /.row -->

              <h2>Many users have already used it in their Linked In background profile</h2>
                    <p></p>


              <div class="row"  style="margin-top:50px;margin-bottom:50px" >
                
                    <div class="col-md-3 col-sm-6 mb-4">
                      <a href="#">
                        <img class="img-fluid" src="/Images/LinkedIn/Linked4.png" alt="">
                      </a>
                    </div>

                    <div class="col-md-3 col-sm-6 mb-4">
                      <a href="#">
                        <img class="img-fluid" src="/Images/LinkedIn/Linked3.png" alt="">
                      </a>
                    </div>

                    <div class="col-md-3 col-sm-6 mb-4">
                      <a href="#">
                        <img class="img-fluid" src="/Images/LinkedIn/Linked2.png" alt="">
                      </a>
                    </div>

                    <div class="col-md-3 col-sm-6 mb-4">
                      <a href="#">
                        <img class="img-fluid" src="/Images/LinkedIn/Linked1.png" alt="">
                      </a>
                    </div>

                  </div>


              <h2>My Profile</h2>
                    <p></p>

             <!-- Content Row -->
              <div class="row" style="margin-top:50px">
                <div class="col-lg-4 mb-4">
                  <div class="card h-50">
                    <h3 class="card-header" style="text-align:center">Email</h3>
                    <div class="card-body" style="width:150px;height:150px;text-align:center;margin-left:100px">
                      <img class="card-img-top" src="Images/Social/12/gmail.png" alt="">
                    </div>
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item"> <a href="#">lordkortex@gmail.com</a></li>
                    </ul>
                  </div>
                </div>
                 <div class="col-lg-4 mb-4">
                  <div class="card h-50">
                    <h3 class="card-header" style="text-align:center">Skype</h3>
                    <div class="card-body" style="width:150px;height:150px;text-align:center;margin-left:100px">
                      <img class="card-img-top" src="Images/Social/12/skype.png" alt="">
                    </div>
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item"> <a href="#">Jhon Fredy Cortes Gaspar</a></li>
                    </ul>
                  </div>
                </div>
                 <div class="col-lg-4 mb-4">
                  <div class="card h-50">
                    <h3 class="card-header" style="text-align:center">LinkedIn</h3>
                    <div class="card-body" style="width:150px;height:150px;text-align:center;margin-left:100px">
                      <img class="card-img-top" src="Images/Social/12/linkedin.png" alt="">
                    </div>
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item">  <a target="_blank" href="https://www.linkedin.com/in/johncortes57">LinkedIn Profile</a></li>
                    </ul>
                  </div>
                </div>
              </div>


               <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

            <hr>
        </div>
        <!-- /.container -->







         <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Salesforce 4 All 2017</p>
      </div>
      <!-- /.container -->
    </footer>

  

        <img src="Images/Original/header-bg-1.png" id="header-bg-1" style="display: none;">
        <img src="Images/Original/header-bg-2.png" id="header-bg-2" style="display: none;">
        <img src="Images/Original/header-bg-3.png" id="header-bg-3" style="display: none;">
        <img src="Images/Original/header-bg-4.png" id="header-bg-4" style="display: none;">

        <img src="Images/Original/header-bg-5.png" id="header-bg-5" style="display: none;">
        <img src="Images/Original/header-bg-6.png" id="header-bg-6" style="display: none;">
        <img src="Images/Original/header-bg-7.png" id="header-bg-7" style="display: none;">
        <img src="Images/Original/header-bg-8.png" id="header-bg-8" style="display: none;">

        <img src="Images/Original/header-bg-9.png" id="header-bg-9" style="display: none;">
        <img src="Images/Original/header-bg-10.png" id="header-bg-10" style="display: none;">
        <img src="Images/Original/header-bg-11.png" id="header-bg-11" style="display: none;">
        <img src="Images/Original/header-bg-12.png" id="header-bg-12" style="display: none;">

        <img src="Images/Original/header-bg-13.png" id="header-bg-13" style="display: none;">
        <img src="Images/Original/header-bg-14.png" id="header-bg-14" style="display: none;">
        <img src="Images/Original/header-bg-15.png" id="header-bg-15" style="display: none;">
        <img src="Images/Original/header-bg-16.png" id="header-bg-16" style="display: none;">

        <img src="Images/OriginalTrailhead/header-bg-1.png" id="header-bg-t1" style="display: none;">
        <img src="Images/OriginalTrailhead/header-bg-2.png" id="header-bg-t2" style="display: none;">
        <img src="Images/OriginalTrailhead/header-bg-3.png" id="header-bg-t3" style="display: none;">
        <img src="Images/OriginalTrailhead/header-bg-4.png" id="header-bg-t4" style="display: none;">

   
         <img src="Images/Certificates/.cert-badge.Certified.Administrator.jpg" id="Salesforce Certified Administrator" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Advanced.Administrator.jpg" id="Salesforce Certified Advanced Administrator" style="display: none;">
        <%--<img src="Images/Certificates/.cert-badge.Certified.Advanced.Developer.jpg" id="Salesforce Certified Platform Developer II" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Developer.jpg" id="Salesforce Certified Platform Developer I" style="display: none;">
        --%><img src="Images/Certificates/.cert-badge.Certified.Sales.Consultant.jpg" id="Salesforce Certified Sales Cloud Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Service.Consultant.jpg" id="Salesforce Certified Service Cloud Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Technical.Architect.jpg" id="Salesforce Certified Technical Architect" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.System.Architect.jpg" id="Salesforce Certified System Architect" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Application.Architect.jpg" id="Salesforce Certified Application Architect" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Pardot.Consultant.jpg" id="Salesforce Certified Pardot Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Pardot.User.jpg" id="Salesforce Certified Pardot Specialist" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.App.Builder.jpg" id="Salesforce Certified Platform App Builder" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Marketing.Cloud.Email.Specialist.jpg" id="Salesforce Certified Marketing Cloud Email Specialist" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Marketing.Cloud.Social.Specialist.jpg" id="Certified Marketing Cloud Social Specialist" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Programmer.I.jpg" id="Salesforce Certified Platform Developer I" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Programmer.II.jpg" id="Salesforce Certified Platform Developer II" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Data.Architecture.and.Management.Specialist.jpg" id="Salesforce Certified Data Architecture & Management Designer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Data.Architecture.and.Management.Specialist.jpg" id="Salesforce Certified Data Architecture and Management Designer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Development.Lifecycle.and.Deployment.Specialist.jpg" id="Salesforce Certified Development Lifecycle and Deployment Designer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Integration.Architecture.Specialist.jpg" id="Salesforce Certified Integration Architecture Designer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Marketing.Cloud.Consultant.jpg" id="Salesforce Certified Marketing Cloud Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Marketing.Cloud.Developer.jpg" id="Salesforce Certified Marketing Cloud Developer" style="display: none;">
        
        <img src="Images/Certificates/.cert-badge.Certified.Sharing.and.Visibility.Designer.jpg" id="Salesforce Certified Sharing and Visibility Designer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Identity.and.Access.Management.Designer.jpg" id="Salesforce Certified Identity and Access Management Designer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Mobile.Solutions.Architecture.Designer.jpg" id="Salesforce Certified Mobile Solutions Architecture Designer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Community.Cloud.Consultant.jpg" id="Salesforce Certified Community Cloud Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.CPQ.Specialist.jpg" id="Salesforce Certified CPQ Specialist" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.B2C.Commerce.Developer.jpg" id="Salesforce Certified B2C Commerce Developer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.B2C.Commerce.Technical.Solution.Designer.jpg" id="Salesforce Certified B2C Technical Solution Designer" style="display: none;">
      <%--  <img src="Images/Certificates/.cert-badge.Certified.Commerce.Cloud.Digital.Developer.jpg" id="YaNoExiste1" style="display: none;">
      --%>  
        <img src="Images/Certificates/.cert-badge.Accredited.Sales.Professional.jpg" id="Accredited Sales Professional" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Accredited.Presales.Professional.jpg" id="Accredited Presales Professional" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Nonprofit.Cloud.Consultant.jpg" id="Salesforce Certified Nonprofit Cloud Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Field.Service.Lightning.Consultant.jpg" id="Salesforce Certified Field Service Lightning" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Field.Service.Lightning.Consultant.jpg" id="Salesforce Certified Field Service Lightning Consultant" style="display: none;">
        
        <img src="Images/Certificates/.cert-badge.Certified.Einstein.Analytics.Discovery.Consultant.png" id="Salesforce Certified Einstein Analytics and Discovery Consultant" style="display: none;">
     
        <img src="Images/Certificates/.cert-badge.Certified.Education.Cloud.Consultant.jpg " id="Salesforce Certified Education Cloud Consultant" style="display: none;">
      
        <img src="Images/Certificates/.cert-badge.Certified.Heroku.Architecture.Designer.png" id="Salesforce Certified Heroku Architecture Designer" style="display: none;">
        
        <img src="Images/Certificates/.cert-badge.Certified.Salesforce.Certified.Marketing.Cloud.Administrator.jpg" id="Salesforce Certified Marketing Cloud Administrator" style="display: none;">
          
        
        <img src="Images/Certificates/Salesforce Accredited B2B Commerce Developer.png" id="Salesforce Accredited B2B Commerce Developer" style="display: none;">
        <img src="Images/Certificates/Salesforce Accredited B2B Commerce Administrator.png" id="Salesforce Accredited B2B Commerce Administrator" style="display: none;">
        <img src="Images/Certificates/Salesforce Certified B2C Commerce Architect.png" id="Salesforce Certified B2C Commerce Architect" style="display: none;">
     
        
         <img src="Images/Certificates/.cert-badge.Certified.Salesforce.Certified.Marketing.Cloud.Administrator.jpg" id="Img2" style="display: none;">
        


        <%--  Se usaron hasta 11/05/2019 cuando salesforce cambio la estructuura de las respuestas xml a json y encripto el id de salesforce de la cuenta y cambio los nombres de los certificados en las respuestas
         <img src="Images/Certificates/.cert-badge.Certified.Administrator.jpg" id="Certified Administrator" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Advanced.Administrator.jpg" id="Certified Advanced Administrator" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Advanced.Developer.jpg" id="Certified Advanced Developer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Developer.jpg" id="Certified Developer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Sales.Consultant.jpg" id="Certified Sales Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Service.Consultant.jpg" id="Certified Service Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Technical.Architect.jpg" id="Certified Technical Architect" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.System.Architect.jpg" id="Certified System Architect" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Application.Architect.jpg" id="Certified Application Architect" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Pardot.Consultant.jpg" id="Certified Pardot Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Pardot.User.jpg" id="Certified Pardot User" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.App.Builder.jpg" id="Certified App Builder" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Marketing.Cloud.Email.Specialist.jpg" id="Certified Marketing Cloud Email Specialist" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Marketing.Cloud.Social.Specialist.jpg" id="Certified Marketing Cloud Social Specialist" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Programmer.I.jpg" id="Certified Programmer I" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Programmer.II.jpg" id="Certified Programmer II" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Data.Architecture.and.Management.Specialist.jpg" id="Certified Data Architecture and Management Specialist" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Development.Lifecycle.and.Deployment.Specialist.jpg" id="Certified Development Lifecycle and Deployment Specialist" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Integration.Architecture.Specialist.jpg" id="Certified Integration Architecture Specialist" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Marketing.Cloud.Consultant.jpg" id="Certified Marketing Cloud Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Sharing.and.Visibility.Designer.jpg" id="Certified Sharing and Visibility Designer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Identity.and.Access.Management.Designer.jpg" id="Certified Identity and Access Management Designer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Mobile.Solutions.Architecture.Designer.jpg" id="Certified Mobile Solutions Architecture Designer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Community.Cloud.Consultant.jpg" id="Certified Community Cloud Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.CPQ.Specialist.jpg" id="Certified CPQ Specialist" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Field.Service.Lightning.Consultant.jpg" id="Certified Field Service Lightning Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Commerce.Cloud.Digital.Developer.jpg" id="Certified Commerce Cloud Digital Developer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Accredited.Sales.Professional.jpg" id="Accredited Sales Professional" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Accredited.Presales.Professional.jpg" id="Accredited Presales Professional" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Nonprofit.Cloud.Consultant.jpg" id="Certified Nonprofit Cloud Consultant" style="display: none;">
        
--%>

       <%-- <img src="Images/Certificates/.cert-badge.Certified.Administrator.jpg" id=".cert-badge.Certified.Administrator" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Advanced.Administrator.jpg" id=".cert-badge.Certified.Advanced.Administrator" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Advanced.Developer.jpg" id=".cert-badge.Certified.Advanced.Developer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Developer.jpg" id=".cert-badge.Certified.Developer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Sales.Consultant.jpg" id=".cert-badge.Certified.Sales.Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Service.Consultant.jpg" id=".cert-badge.Certified.Service.Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Technical.Architect.jpg" id=".cert-badge.Certified.Technical.Architect" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.System.Architect.jpg" id=".cert-badge.Certified.System.Architect" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Application.Architect.jpg" id=".cert-badge.Certified.Application.Architect" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Pardot.Consultant.jpg" id=".cert-badge.Certified.Pardot.Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Pardot.User.jpg" id=".cert-badge.Certified.Pardot.User" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.App.Builder.jpg" id=".cert-badge.Certified.App.Builder" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Marketing.Cloud.Email.Specialist.jpg" id=".cert-badge.Certified.Marketing.Cloud.Email.Specialist" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Marketing.Cloud.Social.Specialist.jpg" id=".cert-badge.Certified.Marketing.Cloud.Social.Specialist" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Programmer.I.jpg" id=".cert-badge.Certified.Programmer.I" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Programmer.II.jpg" id=".cert-badge.Certified.Programmer.II" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Data.Architecture.and.Management.Specialist.jpg" id=".cert-badge.Certified.Data.Architecture.and.Management.Specialist" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Development.Lifecycle.and.Deployment.Specialist.jpg" id=".cert-badge.Certified.Development.Lifecycle.and.Deployment.Specialist" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Integration.Architecture.Specialist.jpg" id=".cert-badge.Certified.Integration.Architecture.Specialist" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Marketing.Cloud.Consultant.jpg" id=".cert-badge.Certified.Marketing.Cloud.Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Sharing.and.Visibility.Designer.jpg" id=".cert-badge.Certified.Sharing.and.Visibility.Designer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Identity.and.Access.Management.Designer.jpg" id=".cert-badge.Certified.Identity.and.Access.Management.Designer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Mobile.Solutions.Architecture.Designer.jpg" id=".cert-badge.Certified.Mobile.Solutions.Architecture.Designer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Community.Cloud.Consultant.jpg" id=".cert-badge.Certified.Community.Cloud.Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.CPQ.Specialist.jpg" id=".cert-badge.Certified.CPQ.Specialist" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Field.Service.Lightning.Consultant.jpg" id=".cert-badge.Certified.Field.Service.Lightning.Consultant" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Certified.Commerce.Cloud.Digital.Developer.jpg" id=".cert-badge.Certified.Commerce.Cloud.Digital.Developer" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Accredited.Sales.Professional.jpg" id=".cert-badge.Accredited.Sales.Professional" style="display: none;">
        <img src="Images/Certificates/.cert-badge.Accredited.Presales.Professional.jpg" id=".cert-badge.Accredited.Presales.Professional" style="display: none;">--%>


       <%-- <div class="cert-badge-certified-commerce-cloud-digital-developer" id=".cert.badge.certified.commerce.cloud.digital.developer" style="display: none;"></div>
        <div class="cert-badge-certified-administrator"  id=".cert.badge.certified.administrator" style="display: none;"></div>
        <div class="cert-badge-certified-advanced-administrator"  id=".cert-badge.certified.advanced.administrator" style="display: none;"></div>
        <div class="cert-badge-certified-app-builder"  id=".cert.badge.certified.app.builder" style="display: none;"></div>
        <div class="cert-badge-certified-cpq-specialist"  id=".cert.badge.certified.cpq.specialist" style="display: none;"></div>
        <div class="cert-badge-certified-development-lifecycle-and-deployment-specialist" id=".cert.badge.certified.development.lifecycle.and.deployment.specialist" style="display: none;"></div>
        <div class="cert-badge-certified-field-service-lightning-consultant" id=".cert.badge.certified.field.service.lightning.consultant" style="display: none;"></div>
        <div class="cert-badge-certified-integration-architecture-specialist" id=".cert.badge.certified.integration.architecture.specialist" style="display: none;"></div>
        <div class="cert-badge-certified-marketing-cloud-email-specialist" id=".cert.badge.certified.marketing.cloud.email.specialist" style="display: none;"></div>
        <div class="cert-badge-certified-pardot-consultant" id=".cert.badge.certified.pardot.consultant" style="display: none;"></div>
        <div class="cert-badge-certified-pardot-user" id=".cert.badge.certified.pardot.user" style="display: none;"></div>
        <div class="cert-badge-certified-sales-consultant" id=".cert.badge.certified.sales.consultant" style="display: none;"></div>
        <div class="cert-badge-certified-service-consultant" id=".cert.badge.certified.service.consultant" style="display: none;"></div>
        <div class="cert-badge-accredited-presales-professional" id=".cert.badge.accredited.presales.professional" style="display: none;"></div>
        <div class="cert-badge-accredited-sales-professional" id=".cert.badge.accredited.sales.professional" style="display: none;"></div>
        <div class="cert-badge-certified-advanced-developer" id=".cert.badge.certified.advanced.developer" style="display: none;"></div>
        <div class="cert-badge-certified-application-architect" id=".cert.badge.certified.application.architect" style="display: none;"></div>
        <div class="cert-badge-certified-community-cloud-consultant" id=".cert.badge.certified.community.cloud.consultant" style="display: none;"></div>
        <div class="cert-badge-certified-data-architecture-and-management-specialist" id=".cert.badge.certified.data.architecture.and.management.specialist" style="display: none;"></div>
        <div class="cert-badge-certified-developer" id=".cert.badge.certified.developer" style="display: none;"></div>
        <div class="cert-badge-certified-identity-and-access-management-designer" id=".cert.badge.certified.identity.and.access.management.designer" style="display: none;"></div>
        <div class="cert-badge-certified-marketing-cloud-consultant" id=".cert.badge.certified.marketing.cloud.consultant" style="display: none;"></div>
        <div class="cert-badge-certified-marketing-cloud-social-specialist" id=".cert.badge.certified.marketing.cloud.social.specialist" style="display: none;"></div>
        <div class="cert-badge-certified-mobile-solutions-architecture-designer" id=".cert.badge.certified.mobile.solutions.architecture.designer" style="display: none;"></div>
        <div class="cert-badge-certified-programmer-i" id=".cert.badge.certified.programmer.i" style="display: none;"></div>
        <div class="cert-badge-certified-programmer-ii" id=".cert.badge.certified.programmer.ii" style="display: none;"></div>
        <div class="cert-badge-certified-sharing-and-visibility-designer" id=".cert.badge.certified.sharing.and.visibility.designer" style="display: none;"></div>
        <div class="cert-badge-certified-system-architect" id=".cert.badge.certified.system.architect" style="display: none;"></div>
        <div class="cert-badge-certified-technical-architect" id=".cert.badge.certified.technical.architect" style="display: none;"></div>--%>



        <script src="Scripts/fabric.min.js" type="text/javascript"></script>
        <script type="text/javascript">

            function redirect() {
                //event.preventDefault();
                //window.location = "http://www.salesforce4all.com/Default.aspx#drawZone?email=" + document.getElementById("email").value + "&indexBackground=" + document.getElementById("imageSelected").selectedIndex;
                window.open("http://www.salesforce4all.com/Default.aspx#drawZone?email=" + document.getElementById("email").value + "&indexBackground=" + document.getElementById("imageSelected").selectedIndex, '_blank');
            }

            jQuery("select.image-picker").imagepicker({
                hide_select: false,
            });

            jQuery("select.image-picker.show-labels").imagepicker({
                hide_select: false,
                show_label: true,
            });

            jQuery("select.image-picker.limit_callback").imagepicker({
                limit_reached: function () { alert('We are full!') },
                hide_select: false
            });

            var container = jQuery("select.image-picker.masonry").next("ul.thumbnails");
            container.imagesLoaded(function () {
                container.masonry({
                    itemSelector: "li",
                });
            });

        </script>
    </form>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


   <script type="text/javascript">
       var qrcode = new QRCode(document.getElementById("qrcode"), {
           width: 100,
           height: 100
       });

       function makeCode() {
           var elText = document.getElementById("textQr");
           qrcode.makeCode(elText.value);
       }

       makeCode();
    </script>

</body>
</html>
